openapi: 3.1.0
info:
  title: Phase III Chat API
  description: AI Chatbot Todo Management API
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /chat:
    post:
      summary: Send chat message
      description: Send a natural language message to the AI assistant
      operationId: sendChatMessage
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limited
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: AI service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /conversations:
    get:
      summary: List user conversations
      description: Get all conversations for the authenticated user
      operationId: listConversations
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /conversations/{conversation_id}:
    get:
      summary: Get conversation details
      description: Get a specific conversation with its messages
      operationId: getConversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: message_limit
          in: query
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Conversation with messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDetailResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 5000
          description: Natural language message from user
          example: "Add a task to buy groceries"
        conversation_id:
          type: string
          format: uuid
          nullable: true
          description: Optional conversation ID to continue existing conversation

    ChatResponse:
      type: object
      required:
        - response
        - conversation_id
      properties:
        response:
          type: string
          description: AI assistant's response message
          example: "I've added 'buy groceries' to your task list!"
        conversation_id:
          type: string
          format: uuid
          description: Conversation ID (new or existing)
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          description: Tools invoked during this interaction

    ToolCall:
      type: object
      required:
        - tool
        - input
        - output
        - status
      properties:
        tool:
          type: string
          enum: [add_task, list_tasks, update_task, delete_task, complete_task]
          description: Name of the MCP tool invoked
        input:
          type: object
          description: Input parameters passed to the tool
        output:
          type: object
          description: Output returned by the tool
        status:
          type: string
          enum: [success, error]
          description: Execution status

    ConversationSummary:
      type: object
      required:
        - id
        - created_at
        - last_activity
        - message_count
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        last_activity:
          type: string
          format: date-time
        message_count:
          type: integer
        preview:
          type: string
          description: First message preview (truncated)

    ConversationListResponse:
      type: object
      required:
        - conversations
        - total
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationSummary'
        total:
          type: integer
          description: Total number of conversations

    Message:
      type: object
      required:
        - id
        - role
        - content
        - created_at
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant, tool]
        content:
          type: string
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          nullable: true
        created_at:
          type: string
          format: date-time

    ConversationDetailResponse:
      type: object
      required:
        - id
        - created_at
        - last_activity
        - messages
      properties:
        id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        last_activity:
          type: string
          format: date-time
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "invalid_input"
        message:
          type: string
          description: Human-readable error message
          example: "Message cannot be empty"
        details:
          type: object
          nullable: true
          description: Additional error details
